# Generated by Django 3.2.4 on 2021-06-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='usersname',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
