# Generated by Django 3.2.4 on 2021-06-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_alter_fcuser_usersname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcuser',
            table='fastcampus_fcuserExample',
        ),
    ]
