# Generated by Django 3.2.4 on 2021-06-28 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name_plural': '장고 사용자'},
        ),
        migrations.RenameField(
            model_name='fcuser',
            old_name='usersname',
            new_name='username',
        ),
    ]
