# Generated by Django 3.2.4 on 2021-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_auto_20210628_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
