# Generated by Django 3.2.4 on 2021-07-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='wirter',
            new_name='writer',
        ),
    ]
